docs: Add a technical documentation for node holders and developers
canow-co/canow-chain pull request #32
Opened 2023-02-27 08:37 UTC by Toktar

2023-03-07 13:51 UTC, alexsdsr requested changes

2023-03-07 13:51 UTC, alexsdsr commented on docs/infrustructure/system-requirements.md
> +Our [packaged releases](https://github.com/canow-co/canow-chain/releases) are currently compiled and tested for `Ubuntu 20.04 LTS`, which is the recommended operating system for installation using in
what about ubuntu 22.04? We use 22.04 in the AWS cloud. It means `canow-chain` works fine on 22.04. I think it's a good idea to ensure that it can be compiled on ubuntu 22.04.

2023-03-07 13:51 UTC, alexsdsr commented on docs/node-setup/canow-node-installation.md
> +docker run -it --rm -p "26657:26657" -p "26656:26656" -p "1317:1317" canow-chain
I think we should remove `--rm` flag from the command. Otherwise the docker container will be removed once it's stopped. All data will be lost.

2023-03-31 14:20 UTC, AlexanderShenshin commented on docs/node-setup/validator-creation.md
> +  --gas-prices="25xarx" \
Seems like a typo: `25xarx` -> `25zarx`

2023-03-31 14:22 UTC, AlexanderShenshin commented on docs/dev-instructions/build-and-install.md
> +### Step 2. Define permissions (optional)
We probably want to remove `Step 2` here.

2023-03-31 14:25 UTC, AlexanderShenshin commented on README.md
> +- Join Canow network like a validator or observer.
Minor correction: `like a validator or observer` -> `as a validator or observer`.

2023-03-31 14:54 UTC, Toktar commented on docs/dev-instructions/build-and-install.md
> +### Step 2. Define permissions (optional)
Why?

2023-03-31 15:06 UTC, AlexanderShenshin approved these changes

2023-03-31 15:09 UTC, merged